create table bucketlist_users(
    id INTEGER primary key generated by default as identity,
    email TEXT not null unique,
    password TEXT not null,
    user_created_time TIMESTAMPTZ default now() not null,
    nickname TEXT not null
);
