create table bucketlist_destinations(
    id INTEGER primary key generated by default as identity,
    destination TEXT not null,
    img TEXT not null,
    coordinate TEXT not null,
    user_id INTEGER references bucketlist_users(id) on delete cascade,
    destination_created_time TIMESTAMPTZ default now() not null
);

