create table bucketlist_todos(
    id INTEGER primary key generated by default as identity,
    user_id INTEGER references bucketlist_users(id) on delete cascade,
    destination_id INTEGER references bucketlist_destinations(id) on delete cascade,
    content TEXT not null,
    checked_active boolean default false not null,
    todo_created_time TIMESTAMPTZ default now() not null
);
